print('===== DESAFIO 02 =====')
dia = input('Qual o dia do seu aniversário?')
mes = input('Qual o mês do seu aniversário?')
anonasc = input('Qual seu ano de nascimento?')
print('Você nasceu no dia', dia, 'de', mes, 'de', anonasc, '. Correto?')
